= Dart Comics

A simple Dart front-end for organizing comic books across formats. The backend is a simple Dart web server.

== Install

=== Prerequisites

* Dart binaries

=== Dart Backend

Dart powers the simple REST-like backend. The web server relies on Dart packages which can be installed with:

----
pub install
----

=== Dart Frontend

These are not strictly needed if you have access to a Dart enabled browser.  But, since Dart enabled browsers are somewhat rare, Dart executables can be used to compile the Dart code into Javascript.

Grab the executable appropriate for you platform from the http:from http://gsdview.appspot.com/dart-editor-archive-continuous/latest/[dart binaries server] (i.e. get dart-linux.zip, dart-macos.zip, or dart-win32.zip).

== Running

To compile the Dart into Javascript, use `dart2js` from the Dart binaries:

----
$ dart2js -opublic/scripts/main.dart.js public/scripts/main.dart
----

The application will automatically fallback to Javascript for browsers that do not support Dart.

To start the backend server, execute the dart application:

----
$ dart app.dart
----
